server.port=8887
github.client.id=dded2a15a8c3a3f544af
github.client.secret=fdc0b9371a62d63ad7d34e4f0ef0e7b8f73516b4
github.redirect.uri=http://localhost:8887/callback
spring.datasource.url=jdbc:h2:~/community
spring.datasource.username=root
spring.datasource.password=123
spring.datasource.driver-class-name=org.h2.Driver

